# Generated by Django 5.0.1 on 2024-01-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="електронна пошта"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
